export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL';

export const ORDERS_GET_REQUEST = 'ORDERS_GET_REQUEST';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_FAIL = 'ORDERS_GET_FAIL';

export const ORDERS_GET_ALL_REQUEST = 'ORDERS_GET_ALL_REQUEST';
export const ORDERS_GET_ALL_SUCCESS = 'ORDERS_GET_ALL_SUCCESS';
export const ORDERS_GET_ALL_FAIL = 'ORDERS_GET_ALL_FAIL';

export const ORDERS_UPDATE_REQUEST = 'ORDERS_UPDATE_REQUEST';
export const ORDERS_UPDATE_SUCCESS = 'ORDERS_UPDATE_SUCCESS';
export const ORDERS_UPDATE_FAIL = 'ORDERS_UPDATE_FAIL';
