export const PROFILEDETAILS_SUCCESS = 'PROFILEDETAILS_SUCCESS';
export const PROFILEDETAILS_FAILURE = 'PROFILEDETAILS_FAILURE';
export const PROFILEDETAILS_REQUEST = 'PROFILEDETAILS_REQUEST';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
